name: paula
description: An initial literacy made by UnB.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 3.5.0+13

environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_datetime_picker: ^1.3.5
  gender_picker: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  http_interceptor: ^1.0.2
  shared_preferences: "^2.0.6"
  page_transition: "^2.0.9"
  audioplayers: ^1.0.1
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  lottie: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/paula01.png
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/fireworks.json

    #Figuras da paula
    - assets/images/paula/paula01.png
    - assets/images/paula/paula02.png
    - assets/images/paula/paula03.png
    - assets/images/paula/paula04.png
    - assets/images/paula/paula05.png
    - assets/images/paula/paula06.png
    - assets/images/paula/paula07.png
    - assets/images/paula/paula08.png
    - assets/images/paula/paula09.png
    - assets/images/paula/paula10.png

    #Figuras das palavras
    - assets/images/words/abacaxi.png
    - assets/images/words/abajur.png
    - assets/images/words/antena.png
    - assets/images/words/apito.png
    - assets/images/words/arroz.png
    - assets/images/words/arvore.png
    - assets/images/words/aviao.png
    - assets/images/words/bebida.png
    - assets/images/words/boia.png
    - assets/images/words/bola.png
    - assets/images/words/caneta.png
    - assets/images/words/capa.png
    - assets/images/words/cavalo.png
    - assets/images/words/dado.png
    - assets/images/words/elefante.png
    - assets/images/words/envelope.png
    - assets/images/words/escada.png
    - assets/images/words/escova.png
    - assets/images/words/esponja.png
    - assets/images/words/estrela.png
    - assets/images/words/igreja.png
    - assets/images/words/iguana.png
    - assets/images/words/iogurte.png
    - assets/images/words/ioio.png
    - assets/images/words/isca.png
    - assets/images/words/lata.png
    - assets/images/words/faca.png
    - assets/images/words/bala.png
    - assets/images/words/meia.png
    - assets/images/words/oculos.png
    - assets/images/words/onibus.png
    - assets/images/words/ovo.png
    - assets/images/words/olho.png
    - assets/images/words/padaria.png
    - assets/images/words/paranoa.png
    - assets/images/words/paranoa_carnes.jpg
    - assets/images/words/paranoa_panificadora.jpg
    - assets/images/words/paranoa_upa.jpg
    - assets/images/words/paranoa_letreiro.jpg
    - assets/images/words/paranoa_tintas.jpg
    - assets/images/words/paranoa_casaNordestina.png
    - assets/images/words/paranoa_casaNordestina.png
    - assets/images/words/paranoa_Distribuidora.png
    - assets/images/words/paranoa_lago1.png
    - assets/images/words/paranoa_lago2.png
    - assets/images/words/paranoa_paroquia.png
    - assets/images/words/paranoa_penaJaca.png
    - assets/images/words/paranoa_tintas1.png
    - assets/images/words/paranoa_Universal.png
    - assets/images/words/seta.png
    - assets/images/words/sorvete.png
    - assets/images/words/um.png
    - assets/images/words/unha.png
    - assets/images/words/urso.png
    - assets/images/words/uva.png
    - assets/images/words/avó.png
    - assets/images/words/avô.png
    - assets/images/words/neto.png
    - assets/images/words/bebe.png
    - assets/images/words/carro.png
    - assets/images/words/mae.png
    - assets/images/words/pai.png
    - assets/images/words/cama.png
    - assets/images/words/lapis.png
    - assets/images/words/criança.png
    - assets/images/words/menino.png
    - assets/images/words/menina.png
    - assets/images/words/cachorro.png
    - assets/images/words/gato.png
    - assets/images/words/vaca.png
    - assets/images/words/lixo.png
    - assets/images/words/escola.png
    - assets/images/words/casa.png
    - assets/images/words/capivara.png
    - assets/images/words/churrasco.png
    - assets/images/words/cafe.png
    - assets/images/words/leite.png
    
  
    
    #Figuras dos selos
    - assets/images/selos/Selo_itapoa_off.png
    - assets/images/selos/Selo_itapoa_on.png
    - assets/images/selos/Selo_paranoa_off.png
    - assets/images/selos/Selo_paranoa_on.png
    - assets/images/selos/Selo_escrita_off.png
    - assets/images/selos/Selo_escrita_on.png
    - assets/images/selos/Selo_vogais_off.png
    - assets/images/selos/Selo_vogais_on.png

    #Logo unb
    - assets/images/UnB_logo.png

    ##Audios Paula

    #Audios paula de bem vindo
    - assets/audios/paula/paula_welcome_1.mp3
    - assets/audios/paula/paula_welcome_2.mp3
    - assets/audios/paula/paula_welcome_3.mp3

    #Audios paula de parabéns
    - assets/audios/paula/paula_parabens_1.mp3
    - assets/audios/paula/paula_parabens_2.mp3
    - assets/audios/paula/paula_parabens_3.mp3

    #Audios lesson_introduction
    - assets/audios/paula/paula_introduction_A.mp3
    - assets/audios/paula/paula_introduction_E.mp3
    - assets/audios/paula/paula_introduction_I.mp3
    - assets/audios/paula/paula_introduction_O.mp3
    - assets/audios/paula/paula_introduction_U.mp3

    #Audios task_mark_vowel
    - assets/audios/paula/paula_selection_A.mp3
    - assets/audios/paula/paula_selection_E.mp3
    - assets/audios/paula/paula_selection_I.mp3
    - assets/audios/paula/paula_selection_O.mp3
    - assets/audios/paula/paula_selection_U.mp3

    #Audios task_select_image
    - assets/audios/paula/paula_selectionImage_A.mp3
    - assets/audios/paula/paula_selectionImage_E.mp3
    - assets/audios/paula/paula_selectionImage_I.mp3
    - assets/audios/paula/paula_selectionImage_O.mp3
    - assets/audios/paula/paula_selectionImage_U.mp3

    #Audios Paula ditongos
    - assets/audios/paula/paula_ditongos.mp3
    - assets/audios/paula/paula_ai.mp3
    - assets/audios/paula/paula_ei.mp3
    - assets/audios/paula/paula_oi.mp3
    - assets/audios/paula/paula_ou.mp3
    - assets/audios/paula/paula_ui.mp3

    #Audios Paula task_words_exemple
    - assets/audios/paula/paula_lessonExample_A.mp3
    - assets/audios/paula/paula_lessonExample_E.mp3
    - assets/audios/paula/paula_lessonExample_I.mp3
    - assets/audios/paula/paula_lessonExample_O.mp3
    - assets/audios/paula/paula_lessonExample_U.mp3

    #Audios Paula lesson_vogais
    - assets/audios/paula/paula_lessonVogais.mp3

    #Audios Paula task_vogal_selection
    - assets/audios/paula/paula_vowelSelection.mp3

    #Audios Paula Paranoa
    - assets/audios/paula/paula_palavraWrite.mp3
    - assets/audios/paula/paula_paranoaWrite.mp3
    - assets/audios/paula/paula_paranoaColorido.mp3
    - assets/audios/paula/paula_paranoaDistribuidoras.mp3
    - assets/audios/paula/paula_paranoaDomingo.mp3
    - assets/audios/paula/paula_paranoaFome.mp3
    - assets/audios/paula/paula_paranoaLago.mp3
    - assets/audios/paula/paula_paranoaWelcome.mp3

    #Audios Paula tente Novamente
    - assets/audios/paula/paula_tryAgain_1.mp3
    - assets/audios/paula/paula_tryAgain_2.mp3

    - assets/audios/paula/paula_completeWords.mp3

    ##Audios palavras geradas por computador
    - assets/audios/words/abacaxi.mp3
    - assets/audios/words/abajur.mp3
    - assets/audios/words/antena.mp3
    - assets/audios/words/apito.mp3
    - assets/audios/words/arroz.mp3
    - assets/audios/words/arvore.mp3
    - assets/audios/words/aviao.mp3
    - assets/audios/words/bebida.mp3
    - assets/audios/words/boia.mp3
    - assets/audios/words/bola.mp3
    - assets/audios/words/caneta.mp3
    - assets/audios/words/capa.mp3
    - assets/audios/words/cavalo.mp3
    - assets/audios/words/dado.mp3
    - assets/audios/words/elefante.mp3
    - assets/audios/words/envelope.mp3
    - assets/audios/words/escada.mp3
    - assets/audios/words/escova.mp3
    - assets/audios/words/esponja.mp3
    - assets/audios/words/estrela.mp3
    - assets/audios/words/igreja.mp3
    - assets/audios/words/iguana.mp3
    - assets/audios/words/iogurte.mp3
    - assets/audios/words/ioio.mp3
    - assets/audios/words/isca.mp3
    - assets/audios/words/lata.mp3
    - assets/audios/words/faca.mp3
    - assets/audios/words/bala.mp3
    - assets/audios/words/meia.mp3
    - assets/audios/words/oculos.mp3
    - assets/audios/words/olho.mp3
    - assets/audios/words/onibus.mp3
    - assets/audios/words/ovo.mp3
    - assets/audios/words/padaria.mp3
    - assets/audios/words/paranoa.mp3
    - assets/audios/words/seta.mp3
    - assets/audios/words/sorvete.mp3
    - assets/audios/words/um.mp3
    - assets/audios/words/unha.mp3
    - assets/audios/words/urso.mp3
    - assets/audios/words/uva.mp3
    - assets/audios/words/avó.mp3
    - assets/audios/words/avô.mp3
    - assets/audios/words/neto.mp3
    - assets/audios/words/bebe.mp3
    - assets/audios/words/carro.mp3
    - assets/audios/words/mae.mp3
    - assets/audios/words/pai.mp3
    - assets/audios/words/cama.mp3
    - assets/audios/words/lapis.mp3
    - assets/audios/words/crianca.mp3
    - assets/audios/words/menino.mp3
    - assets/audios/words/menina.mp3
    - assets/audios/words/cachorro.mp3
    - assets/audios/words/gato.mp3
    - assets/audios/words/vaca.mp3
    - assets/audios/words/lixo.mp3
    - assets/audios/words/escola.mp3
    - assets/audios/words/casa.mp3
    - assets/audios/words/capivara.mp3
    - assets/audios/words/churrasco.mp3
    - assets/audios/words/cafe.mp3
    - assets/audios/words/leite.mp3
    - assets/audios/words/paranoa_carnes.mp3
    - assets/audios/words/paranoa_casaNordestina.mp3
    - assets/audios/words/paranoa_distribuidora.mp3
    - assets/audios/words/paranoa_lago.mp3
    - assets/audios/words/paranoa_panificadora.mp3
    - assets/audios/words/paranoa_paroquia.mp3
    - assets/audios/words/paranoa_penaJaca.mp3
    - assets/audios/words/paranoa_tintas.mp3
    - assets/audios/words/paranoa_tintas1.mp3
    - assets/audios/words/paranoa_universal.mp3
    - assets/audios/words/paranoa_upa.mp3

    - assets/audios/sucess_sound.mp3
    - assets/audios/failed_sound.mp3
    - assets/audios/congrats_1.mp3

    - assets/alphabet/letter-a.png
    - assets/alphabet/letter-e.png
    - assets/alphabet/letter-i.png
    - assets/alphabet/letter-o.png
    - assets/alphabet/letter-u.png

    #Audios Itapoã
    - assets/audios/paula/paula_tour_itapoa.mp3
    - assets/audios/words/itapoa.mp3
    - assets/audios/words/panificadora_izadora.mp3
    - assets/audios/paula/audio_pegar_onibus.mp3
    - assets/audios/words/ponte_paranoa.mp3
    - assets/audios/paula/passar_pela_ponte.mp3
    - assets/audios/paula/escrita_itapoa.mp3
    - assets/audios/paula/escrita_onibus.mp3
    - assets/audios/words/praça.mp3
    - assets/audios/words/moto.mp3
    - assets/audios/words/avenida.mp3
    - assets/audios/words/hospital.mp3
    - assets/audios/words/farmacia.mp3
    - assets/audios/words/celular.mp3
    - assets/audios/words/computador.mp3
    - assets/audios/words/copo.mp3
    - assets/audios/words/chave.mp3
    - assets/audios/words/relogio.mp3
    - assets/audios/words/bicicleta.mp3
    - assets/audios/words/mochila.mp3
    - assets/audios/words/colher.mp3
    - assets/audios/words/garfo.mp3
    - assets/audios/words/panela.mp3
    - assets/audios/words/cadeira.mp3


    # Imagens Itapoã
    - assets/images/words/itapoa_madeira.png
    - assets/images/words/itapoa_panificadora.png
    - assets/images/words/itapoa.png
    - assets/images/words/onibus_itapoa.png
    - assets/images/words/ponte.png
    - assets/images/words/praça.jpg
    - assets/images/words/moto.png
    - assets/images/words/avenida.jpg
    - assets/images/words/hospital.png
    - assets/images/words/farmacia.png
    - assets/images/words/celular.png
    - assets/images/words/computador.png
    - assets/images/words/copo.png
    - assets/images/words/chave.png
    - assets/images/words/relogio.png
    - assets/images/words/bicicleta.png
    - assets/images/words/mochila.png
    - assets/images/words/colher.png
    - assets/images/words/garfo.png
    - assets/images/words/panela.png
    - assets/images/words/cadeira.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Norican
      fonts:
        - asset: assets/fonts/Norican-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
