name: paula
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_datetime_picker: ^1.3.5
  gender_picker: ^1.1.0
  flutter:
    sdk: flutter

  http: ^0.13.4
  http_interceptor: ^1.0.2
  shared_preferences: "^2.0.6"
  page_transition: "^2.0.9"
  audioplayers: ^1.0.1
  provider: ^6.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/Avatar-Maker(2).png
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/paula/Avatar-Maker(1).png
    - assets/images/paula/Avatar-Maker(2).png
    - assets/images/paula/Avatar-Maker(4).png

    - assets/images/words/arvore.png
    - assets/images/words/oculos.png
    - assets/images/words/uva.png
    - assets/images/words/escada.png
    - assets/images/words/lata.png
    - assets/images/words/aviao.png
    - assets/images/words/abacaxi.png
    - assets/images/words/abajur.png
    - assets/images/words/antena.png
    - assets/images/words/apito.png
    - assets/images/words/arroz.png
    - assets/images/words/bebida.png
    - assets/images/words/boia.png
    - assets/images/words/bola.png
    - assets/images/words/caneta.png
    - assets/images/words/capa.png
    - assets/images/words/cavalo.png
    - assets/images/words/dados.png
    - assets/images/words/envelope.png
    - assets/images/words/iguana.png
    - assets/images/words/ioio.png
    - assets/images/words/meia.png
    - assets/images/words/onibus.png
    - assets/images/words/ovo.png
    - assets/images/words/padaria.png
    - assets/images/words/seta.png

    - assets/images/selos/Selo_diario_off.png
    - assets/images/selos/Selo_mensal_off.png
    - assets/images/selos/Selo_palavras_off.png
    - assets/images/selos/Selo_silabas_off.png
    - assets/images/selos/Selo_vogais_off.png
    - assets/images/selos/Selo_vogais.png

    - assets/images/fireworks.png
    - assets/images/patience.png
    - assets/images/sorvete.png

    - assets/audios/paula/paula01.mp3
    - assets/audios/paula/paula02.ogg
    - assets/audios/paula/completeAsPalavras.mp4
    - assets/audios/paula/exemplosA.mp4
    - assets/audios/paula/introductionA.mp4
    - assets/audios/paula/introductionE.mp4
    - assets/audios/paula/introductionI.mp4
    - assets/audios/paula/introductionO.mp4
    - assets/audios/paula/introductionU.mp4
    - assets/audios/paula/selecioneA.mp4
    - assets/audios/paula/selecioneAsVogais.mp4
    - assets/audios/paula/voceEstaIndoBem.mp4

    - assets/audios/words/aviao.mp3
    - assets/audios/words/abacaxi.mp3
    - assets/audios/words/lata.mp3
    - assets/audios/words/uva.mp3
    - assets/audios/words/arvore.mp3
    - assets/audios/words/escada.mp3
    - assets/audios/words/oculos.mp3
    - assets/audios/words/bebida.mp3
    - assets/audios/words/boia.mp3
    - assets/audios/words/bola.mp3
    - assets/audios/words/caneta.mp3
    - assets/audios/words/capa.mp3
    - assets/audios/words/cavalo.mp3
    - assets/audios/words/dado.mp3
    - assets/audios/words/envelope.mp3
    - assets/audios/words/iguana.mp3
    - assets/audios/words/ioio.mp3
    - assets/audios/words/meia.mp3
    - assets/audios/words/ovo.mp3
    - assets/audios/words/padaria.mp3
    - assets/audios/words/onibus.mp3

    - assets/audios/sucess_sound.mp3
    - assets/audios/failed_sound.mp3
    - assets/audios/marqueA.ogg

    - assets/alphabet/letter-a.png
    - assets/alphabet/letter-e.png
    - assets/alphabet/letter-i.png
    - assets/alphabet/letter-o.png
    - assets/alphabet/letter-u.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
